- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 instance
      ec2:
        instance_type: t2.micro
        image: ami-00ddb0e5626798373
        region: us-east-1
        key_name: test
        vpc_subnet_id: subnet-f5e09efb
        assign_public_ip: yes
        wait: yes
        count: 1
        aws_access_key: "{{access_key}}"
        aws_secret_key: "{{secret_key}}"
        security_token: "{{security_token}}"